=== sklintyg/intygstjanst/migration-tool/mc2wc/mc2wc-common/src/main/resources/schema/mc2wc-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:inera:certificates:mc2wc:1"
  xmlns:tns="urn:inera:certificates:mc2wc:1" elementFormDefault="qualified">

  <complexType name="certificateType">
    <sequence>
      <element name="certificateId" type="string"></element>
      <element name="certificateType" type="string"></element>
      <element name="careUnitId" type="string"></element>
      <element name="patient" type="tns:patientType"></element>
      <element name="sent" type="dateTime" maxOccurs="1" minOccurs="0"></element>
      <element name="created" type="dateTime"></element>
      <element name="origin" type="string"></element>
      <element name="migratedFrom" type="string"></element>
      <element name="contents" type="base64Binary"></element>
    </sequence>
  </complexType>

  <complexType name="migrationMessageType">
    <sequence>
      <element name="certificateId" type="string"></element>
      <element name="certificate" type="tns:certificateType"
        maxOccurs="1" minOccurs="0">
      </element>
      <element name="questions" type="tns:questionType"
        maxOccurs="unbounded" minOccurs="0">
      </element>
    </sequence>
  </complexType>

  <complexType name="questionType">
    <sequence>
      <element name="certificateId" type="string"></element>
      <element name="certificateType" type="string"></element>
      <element name="certificateSigned" type="dateTime" maxOccurs="1" minOccurs="0"></element>
      <element name="externalReference" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="patient" type="tns:patientType"></element>
      <element name="carePerson" type="tns:carePersonType"></element>
      <element name="subject" type="tns:questionSubjectType"></element>
      <element name="caption" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="sent" type="dateTime" maxOccurs="1" minOccurs="0"></element>
      <element name="signed" type="dateTime" maxOccurs="1" minOccurs="0"></element>
      <element name="originator" type="tns:questionOriginatorType">
      </element>
      <element name="status" type="tns:statusType"></element>
      <element name="questionText" type="string"></element>
      <element name="questionLastAnswerDate" type="date" maxOccurs="1" minOccurs="0"></element>
      <element name="answer" type="tns:answerType" maxOccurs="1"
        minOccurs="0">
      </element>
      <element name="supplement" type="tns:supplementType"
        maxOccurs="unbounded" minOccurs="0">
      </element>
    </sequence>
  </complexType>

  <complexType name="careGiverType">
    <sequence>
      <element name="id" type="string"></element>
      <element name="name" type="string"></element>
    </sequence>
  </complexType>

  <complexType name="careUnitType">
    <sequence>
      <element name="id" type="string"></element>
      <element name="name" type="string"></element>
            <element name="workplaceCode" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="phone" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="email" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="postalAddress" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="postalNumber" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="postalCity" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="careGiver" type="tns:careGiverType"
        maxOccurs="1" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="carePersonType">
    <sequence>
      <element name="personId" type="string"></element>
      <element name="fullName" type="string"></element>
      <element name="prescriptionCode" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="careUnit" type="tns:careUnitType"
        maxOccurs="1" minOccurs="1"></element>
    </sequence>
  </complexType>

  <element name="migrationMessage" type="tns:migrationMessageType"></element>

  <complexType name="migrationReplyType">
    <sequence>
      <element name="result" type="tns:migrationResultType"
        maxOccurs="1" minOccurs="1"></element>
      <element name="message" type="string" maxOccurs="1"
        minOccurs="0"></element>
    </sequence>
  </complexType>

  <simpleType name="migrationResultType">
    <restriction base="string">
      <enumeration value="OK"></enumeration>
      <enumeration value="DUPLICATE"></enumeration>
      <enumeration value="ERROR"></enumeration>
    </restriction>
  </simpleType>

  <element name="migrationReply" type="tns:migrationReplyType"></element>

  <complexType name="patientType">
    <sequence>
      <element name="personId" type="string"></element>
      <element name="fullName" type="string"></element>
    </sequence>
  </complexType>

  <simpleType name="certificateOriginatorType">
    <restriction base="string">
      <enumeration value="APPLICATION"></enumeration>
      <enumeration value="QUESTION_CARE"></enumeration>
      <enumeration value="QUESTION_FK"></enumeration>
    </restriction>
  </simpleType>

  <simpleType name="questionSubjectType">
    <restriction base="string">
      <enumeration value="WORK_PROLONGING"></enumeration>
      <enumeration value="MEETING"></enumeration>
      <enumeration value="KOMPLEMENTING"></enumeration>
      <enumeration value="MAKULERING"></enumeration>
      <enumeration value="CONTACT"></enumeration>
      <enumeration value="REMINDER"></enumeration>
      <enumeration value="OTHER"></enumeration>
    </restriction>
  </simpleType>

  <complexType name="supplementType">
    <sequence>
      <element name="field" type="string"></element>
      <element name="text" type="string"></element>
    </sequence>
  </complexType>

  <simpleType name="questionOriginatorType">
    <restriction base="string">
      <enumeration value="FK"></enumeration>
      <enumeration value="CARE"></enumeration>
    </restriction>
  </simpleType>

  <simpleType name="statusType">
    <restriction base="string">
      <enumeration value="CREATED"></enumeration>
      <enumeration value="EDITED"></enumeration>
      <enumeration value="PRINTED"></enumeration>
      <enumeration value="SENT"></enumeration>
      <enumeration value="SIGNED"></enumeration>
      <enumeration value="SIGNED_AND_SENT"></enumeration>
      <enumeration value="SENT_HANDLED"></enumeration>
      <enumeration value="SENT_UNHANDLED"></enumeration>
    </restriction>
  </simpleType>


  <complexType name="answerType">
    <sequence>
      <element name="text" type="string"></element>
      <element name="signed" type="dateTime" maxOccurs="1" minOccurs="0"></element>
      <element name="sent" type="dateTime" maxOccurs="1" minOccurs="0"></element>
      <element name="status" type="tns:statusType"></element>
    </sequence>
  </complexType>
</schema>

=== sklintyg/intygstjanst/migration-tool/mc2wc/mc2wc-receiver/src/test/resources/testdata/mc2wc-test-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<migrationMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:inera:certificates:mc2wc:1"
                  xsi:schemaLocation="urn:inera:certificates:mc2wc:1 mc2wc-schema.xsd ">
  <certificate>
    <certificateId>certificateId</certificateId>
    <certificateType>certificateType</certificateType>
    <careUnitId>careUnitId</careUnitId>
    <patient>
      <personId>personId</personId>
      <fullName>fullName</fullName>
    </patient>
    <sent>2001-12-31T12:00:00</sent>
    <created>2001-12-31T12:00:00</created>
    <origin>origin</origin>
    <migratedFrom>migratedFrom</migratedFrom>
    <contents>MA==</contents>
  </certificate>
  <questions>
    <certificateId>certificateId</certificateId>
    <certificateType>certificateType</certificateType>
    <certificateSigned>2001-12-31T12:00:00</certificateSigned>
    <externalReference>externalReference</externalReference>
    <patient>
      <personId>personId</personId>
      <fullName>fullName</fullName>
    </patient>
    <carePerson>
      <personId>personId</personId>
      <fullName>fullName</fullName>
      <prescriptionCode>prescriptionCode</prescriptionCode>
      <careUnit>
        <workplaceCode>workplaceCode</workplaceCode>
        <id>id</id>
        <name>name</name>
        <phone>phone</phone>
        <email>email</email>
        <postalAddress>postalAddress</postalAddress>
        <postalNumber>postalNumber</postalNumber>
        <postalCity>postalCity</postalCity>
        <careGiver>
          <id>id</id>
          <name>name</name>
        </careGiver>
      </careUnit>
    </carePerson>
    <subject>WORK_PROLONGING</subject>
    <caption>caption</caption>
    <sent>2001-12-31T12:00:00</sent>
    <signed>2001-12-31T12:00:00</signed>
    <originator>FK</originator>
    <status>CREATED</status>
    <questionText>questionText</questionText>
    <questionLastAnswerDate>2001-01-01</questionLastAnswerDate>
    <answer>
      <text>text</text>
      <signed>2001-12-31T12:00:00</signed>
      <sent>2001-12-31T12:00:00</sent>
      <status>CREATED</status>
    </answer>
    <supplement>
      <field>field</field>
      <text>text</text>
    </supplement>
  </questions>
</migrationMessage>
